### ISSUE TITLE
paying to own loki/b-loki address stoping auto swap.

### ISSUE THREAD

**Issue by frndxyz** [loki-project/loki-binance-bridge#8]
if paying swap to own loki/b-loki  address stoping auto swap.

Transaction balance: 18.00120557 XXX
  Swap balance: 12.00120557 XXX
  Balances do not match. Aborting!

**Comment by Mikunj** [comment]
Uhm i didn't understand the question very clearly but if you're asking why it's aborting and saying `Balances do not match` then i can answer that.

Since we're dealing with real currency here, we need to be absolutely sure that the money coming in is the same as the money going out. With the bridge the money coming in (**Transaction balance**) gets stored in a database for later processing (**Swap balance**).

This error basically means that you got more money coming in than what we have recorded in the database. A simple solution would be to sweep the balance `npm run sweep` and it will try and put the incoming currency into the database.

If that doesn't work then it detected incoming transactions from another source and in that case i would suggest you use a dedicated wallet for the bridge.

**Comment by Mikunj** [comment]
Closing since no further input has been provided
